<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="1.204" timestamp="2025-04-16T12:57:33.810910+00:00" hostname="9h4nlh"><testcase classname="" name="tests.test_core" time="0.000"><error message="collection failure">ImportError while importing test module '/project/sandbox/user-workspace/CacheXSSDetector/tests/test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/python/3.10.13/lib/python3.10/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
/usr/local/python/3.10.13/lib/python3.10/site-packages/_pytest/pathlib.py:587: in import_path
    importlib.import_module(module_name)
/usr/local/python/3.10.13/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
/usr/local/python/3.10.13/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/test_core.py:13: in &lt;module&gt;
    from reporting_module import ReportGenerator, RiskAssessor
reporting_module/__init__.py:8: in &lt;module&gt;
    from CacheXSSDetector.reporting_module.risk_assessment import RiskAssessor
E   ModuleNotFoundError: No module named 'CacheXSSDetector'</error></testcase></testsuite></testsuites>